In [1]:
import numpy as np

In [3]:
a =np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
a1 = np.arange(1,10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.min(a1)

1

In [11]:
np.max(a1)

9

In [13]:
np.split(a,1)

[array([1, 2, 3, 4, 5, 6, 7, 8])]

In [16]:
r = np.arange(1,10)
np.split(r,1)

[array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [18]:
np.split(a,2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [21]:
np.split(a,(2,2))

[array([1, 2]), array([], dtype=int32), array([3, 4, 5, 6, 7, 8])]

In [22]:
np.split(a,(4,2))

[array([1, 2, 3, 4]), array([], dtype=int32), array([3, 4, 5, 6, 7, 8])]

In [23]:
np.split(a,(2,4))

[array([1, 2]), array([3, 4]), array([5, 6, 7, 8])]

In [26]:
a = np.arange(1,10).reshape(3,3)
a1 = np.arange(11,20).reshape(3,3)

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [29]:
np.add(a,a1)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [31]:
np.subtract(a1,a)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [32]:
np.multiply(a1,a)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [33]:
np.divide(a,a1)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [34]:
np.min(a)

1

In [35]:
np.min(a1)

11

In [36]:
np.max(a1)

19

In [37]:
np.max(a)

9

In [39]:
np.shape(a)

(3, 3)

In [40]:
np.shape(a1)

(3, 3)

In [41]:
np.concatenate((a,a1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
np.concatenate((a,a1),axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [44]:
np.vstack((a,a1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [45]:
np.hstack((a,a1))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [46]:
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [49]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.median(a)

5.0

In [51]:
a = np.arange(1,10).reshape(3,3)
a1 = np.arange(11,20).reshape(3,3)

In [52]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [54]:
np.median(a1)

15.0

In [55]:
np.mean(a)

5.0

In [56]:
np.mean(a1)

15.0

In [58]:
np.max(a)

9

In [60]:
d = np.arange(1,101).reshape(10,10)
d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [63]:
d[1:9,1:9]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79],
       [82, 83, 84, 85, 86, 87, 88, 89]])

In [64]:
d[1:9,9:1]

array([], shape=(8, 0), dtype=int32)

In [65]:
d.ndim

2

In [68]:
u = np.arange(1,101).reshape(4,5,5)
u

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [69]:
u.ndim

3

In [71]:
u.shape

(4, 5, 5)

In [73]:
u = np.arange(1,101).reshape(20,5)
u

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [1]:
from random import*

In [2]:
import numpy as np

In [43]:
np.random.random()

0.6650861543272583

In [44]:
np.random.random(5)

array([0.82582863, 0.44361352, 0.9541177 , 0.63025831, 0.14499749])

In [45]:
np.random.random((3,3,5))

array([[[0.26961052, 0.53839312, 0.65491894, 0.7894778 , 0.0331269 ],
        [0.542438  , 0.17353271, 0.77235033, 0.74135398, 0.3071263 ],
        [0.15876232, 0.76963486, 0.8288288 , 0.38740755, 0.89035458]],

       [[0.50765488, 0.51991171, 0.88044677, 0.29800307, 0.10390002],
        [0.34094681, 0.94415961, 0.8826293 , 0.65712136, 0.91416464],
        [0.49678249, 0.38990972, 0.92416691, 0.71744142, 0.32636567]],

       [[0.52901309, 0.61135981, 0.15570334, 0.3474348 , 0.69433503],
        [0.40099291, 0.94137792, 0.21773881, 0.57084695, 0.08378509],
        [0.41150166, 0.36305826, 0.79386475, 0.82897163, 0.9637362 ]]])

In [47]:
np.random.random((2,3,3))

array([[[0.26606049, 0.6535772 , 0.19356163],
        [0.11609141, 0.7608494 , 0.42783805],
        [0.3790916 , 0.40231396, 0.16892515]],

       [[0.54183132, 0.2026139 , 0.74181034],
        [0.67343651, 0.64116045, 0.83598625],
        [0.93594316, 0.52111198, 0.26130008]]])

In [48]:
np.random.randint(1,14)

11

In [60]:
np.random.randint(1,14,(3,2))

array([[ 5,  9],
       [11,  8],
       [ 9,  6]])

In [62]:
np.random.randint(1,14,(3,2,5))

array([[[11,  2, 11,  4, 10],
        [ 6,  2, 10,  8, 10]],

       [[ 9,  8,  3,  6, 10],
        [ 5,  8, 11,  1,  7]],

       [[11,  9,  3,  4,  1],
        [13,  5,  4, 12,  3]]])

In [63]:
np.random.rand(3,4)

array([[0.80791676, 0.53785926, 0.61321773, 0.44919866],
       [0.05160928, 0.25155709, 0.92295812, 0.43183748],
       [0.95099167, 0.72752815, 0.60811048, 0.6160415 ]])

In [65]:
a = np.arange(15,28)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [66]:
np.random.choice(a)

17

In [86]:
np.random.permutation(a)
np.random.choice(a)

20

In [87]:
a = np.arange(1111,9999)
np.random.permutation(a)
np.random.choice(a)

3075

In [92]:
np.random.normal()

0.07487950825082577

In [95]:
np.random.normal(50,15,100)

array([50.05896606, 50.31119683, 32.51084043, 51.28863171, 67.69808281,
       56.29252274, 40.20598746, 49.62108734, 61.45351796, 40.20332261,
       74.1196622 , 32.21449133, 61.49996719, 52.24638529, 62.58834221,
       61.99796037, 59.9554849 , 62.95177291, 39.49695967, 78.84849795,
       17.66209054, 50.40775923, 36.38325279, 69.15067349, 49.98767107,
       32.95916155, 43.72052733, 67.01823136, 34.39426291, 69.75799053,
       39.10206388, 50.46392566, 60.19742008, 39.59984864, 43.43780916,
       61.41601574, 41.97392006, 46.54362059, 67.96881635, 42.25623225,
       51.13435151, 37.31193433, 73.72459738, 69.85568784, 58.04742841,
       61.43645065, 67.23896503, 69.90232993, 22.57200931, 58.99333044,
       50.82711861, 64.49032146, 55.05991121, 41.12014893, 52.3428944 ,
       47.33128771, 69.41852516, 32.09465515, 50.12199317, 31.51029433,
       58.30762525, 34.15838724, 35.41517758, 41.69138218, 44.36882393,
       46.98312658, 63.12109446, 46.67339385, 21.55435247, 42.85

In [96]:
np.random.uniform(-1,0,100)

array([-0.71756338, -0.72244791, -0.91736853, -0.75074019, -0.80967847,
       -0.54598523, -0.68440795, -0.24435987, -0.64344392, -0.01809574,
       -0.13054791, -0.22529021, -0.33042111, -0.96548282, -0.4171042 ,
       -0.28145301, -0.29093776, -0.30917162, -0.56697943, -0.41806884,
       -0.61490899, -0.32946055, -0.45431553, -0.21211566, -0.80817324,
       -0.26289689, -0.84694594, -0.14478783, -0.23370431, -0.38600468,
       -0.65870689, -0.857238  , -0.57139192, -0.83097086, -0.13321034,
       -0.49356753, -0.08211874, -0.08825405, -0.74028011, -0.06922535,
       -0.61805639, -0.01200013, -0.7589047 , -0.15662708, -0.66229088,
       -0.86978809, -0.48845899, -0.14208898, -0.90269891, -0.52421527,
       -0.86905506, -0.63944817, -0.04706186, -0.08939075, -0.06299556,
       -0.90413403, -0.15277034, -0.5144773 , -0.44301261, -0.26726439,
       -0.11421544, -0.55141985, -0.79556117, -0.53008906, -0.41348891,
       -0.2010046 , -0.86467685, -0.82534568, -0.37427864, -0.30

In [98]:
a = np.random.randint(1,52,15)
a

array([38, 20, 22, 31, 12, 27, 27, 32,  5, 21,  8, 21, 12, 36, 40])

In [99]:
sorted(a)

[5, 8, 12, 12, 20, 21, 21, 22, 27, 27, 31, 32, 36, 38, 40]

In [100]:
np.sort(a)

array([ 5,  8, 12, 12, 20, 21, 21, 22, 27, 27, 31, 32, 36, 38, 40])

In [101]:
a = np.arange(1,200)

In [102]:
np.mean(a)

100.0

In [104]:
np.median(a)

100.0

In [105]:
np.std(a)

57.445626465380286

In [106]:
np.var(a)

3300.0

In [108]:
a = np.random.randint(1,500,(3,5,5))
a

array([[[299, 130, 485, 405, 413],
        [ 58, 268, 380, 481,  45],
        [192, 499, 453, 284, 342],
        [364, 372, 451,  23, 409],
        [225, 421, 360, 179, 120]],

       [[198, 136, 119, 149, 470],
        [ 65, 294, 303, 182, 362],
        [130, 111, 153, 249, 228],
        [255, 147,  80, 199, 163],
        [246,  67, 233, 340, 266]],

       [[273,  53, 361, 255,  32],
        [ 72, 223, 373, 319, 345],
        [205, 189, 387, 174,  22],
        [478,  49, 487,  17,  70],
        [185, 352, 157, 201, 305]]])

In [109]:
np.sort(a)

array([[[130, 299, 405, 413, 485],
        [ 45,  58, 268, 380, 481],
        [192, 284, 342, 453, 499],
        [ 23, 364, 372, 409, 451],
        [120, 179, 225, 360, 421]],

       [[119, 136, 149, 198, 470],
        [ 65, 182, 294, 303, 362],
        [111, 130, 153, 228, 249],
        [ 80, 147, 163, 199, 255],
        [ 67, 233, 246, 266, 340]],

       [[ 32,  53, 255, 273, 361],
        [ 72, 223, 319, 345, 373],
        [ 22, 174, 189, 205, 387],
        [ 17,  49,  70, 478, 487],
        [157, 185, 201, 305, 352]]])

In [110]:
l = "Learning Python"

In [111]:
l1 = np.array(l)
l1

array('Learning Python', dtype='<U15')

In [113]:
np.char.swapcase(l1)

array('lEARNING pYTHON', dtype='<U15')

In [114]:
np.char.swapcase(l)

array('lEARNING pYTHON', dtype='<U15')

In [116]:
l = ["asd","adf","wer","ghy"]
l1 = []
for i in l:
    i.upper()
    l1.append(i.upper())
l1

['ASD', 'ADF', 'WER', 'GHY']

In [117]:
np.char.upper(l)

array(['ASD', 'ADF', 'WER', 'GHY'], dtype='<U3')

In [120]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.
