In [2]:
import numpy as np

In [5]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
len(a)

15

In [10]:
r = a.reshape(3,5)
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
r.min()

1

In [13]:
np.min(r)

1

In [14]:
r.max()

15

In [16]:
np.max(r)

15

In [18]:
np.sum(r)

120

In [19]:
np.mean(r)

8.0

In [20]:
np.median(r)

8.0

In [22]:
a2 = np.arange(1,16).reshape(3,5)
a3 = np.arange(16,31).reshape(3,5)

In [23]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
a3

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
# mathematical operation
np.add(a2,a3)

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45]])

In [27]:
np.subtract(a3,a2)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [28]:
np.multiply(a2,a3)

array([[ 16,  34,  54,  76, 100],
       [126, 154, 184, 216, 250],
       [286, 324, 364, 406, 450]])

In [29]:
np.divide(a2,a3)

array([[0.0625    , 0.11764706, 0.16666667, 0.21052632, 0.25      ],
       [0.28571429, 0.31818182, 0.34782609, 0.375     , 0.4       ],
       [0.42307692, 0.44444444, 0.46428571, 0.48275862, 0.5       ]])

In [46]:
a2 = np.arange(1,16).reshape(3,5)
a3 = np.arange(16,31).reshape(3,5)

In [47]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [48]:
a3

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [45]:
n = np.sum(a2,axis = 0)
n

array([18, 21, 24, 27, 30])

In [49]:
n = np.sum(a2,axis = 1)
n

array([15, 40, 65])

In [30]:
np.sin(a2)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [31]:
np.cos(a3)

array([[-0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206],
       [-0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281],
       [ 0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145]])

In [32]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [33]:
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [34]:
# joining
np.concatenate((a2,a3))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
np.concatenate((a2,a3),axis = 1)

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

In [36]:
np.vstack((a2,a3))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
np.hstack((a2,a3))

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

In [41]:
np.ravel(a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
a2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
# slicing
a4 = np.arange(1,91).reshape(9,10)
a4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [52]:
a4[0:7]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [54]:
a4[0:8]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [55]:
a4[0:8,1:9]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79]])

In [56]:
np.split(a2,3)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]])]

In [58]:
a5 = np.arange(1,16)
a5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
np.split(a5,3)

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15])]

In [60]:
np.split(a5,5)

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15])]

In [61]:
np.split(a5,[4])

[array([1, 2, 3, 4]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [63]:
np.split(a5,[4,9])

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15])]

In [64]:
np.split(a5,[4,9,14])

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15])]

In [65]:
a5.argmin()

0

In [66]:
a5.argmax()

14

In [74]:
a = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[8,9,6]]])
a

array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 6, 7],
        [8, 9, 6]]])

In [75]:
a.ndim

3