In [1]:
import numpy as np

In [2]:
l = [12,23,34,45,56]

In [4]:
a = np.array(l)
a

array([12, 23, 34, 45, 56])

In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [8]:
a1 =np.array([[[1,2,3],[4,56,7],[6,7,8]],[[3,4,5],[4,5,6],[3,4,5]],[[7,8,9],[7,6,5],[4,7,8]]])
a1

array([[[ 1,  2,  3],
        [ 4, 56,  7],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 4,  5,  6],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [ 7,  6,  5],
        [ 4,  7,  8]]])

In [9]:
a1.ndim

3

In [10]:
a1.shape

(3, 3, 3)

In [11]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
for i in range (2,8):
    print(i)

2
3
4
5
6
7


In [15]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [17]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [19]:
np.linspace(1,100,25)

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [20]:
np.linspace(1,100,50)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [22]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
a = np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
a.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [29]:
a2 = a.reshape(4,2,2)
a2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [28]:
len(a)

16

In [30]:
len(a2)

4

In [33]:
len(a2)

4

In [35]:
a2 = np.arange(1,16).reshape(3,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
a2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
a2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
np.ravel(a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
a2.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [43]:
a1 = np.arange(1,13).reshape(3,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a2 = np.arange(13,25).reshape(3,4)
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [46]:
np.add(a1,a2)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [47]:
np.subtract(a2,a1)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [48]:
np.multiply(a1,a2)

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [51]:
np.divide(a1,a2)

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

In [52]:
np.divide(a2,a1)

array([[13.        ,  7.        ,  5.        ,  4.        ],
       [ 3.4       ,  3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909,  2.        ]])

In [53]:
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [55]:
np.sum(a2)

222

In [57]:
np.min(a2)

13

In [58]:
a2.min()

13

In [59]:
a2.argmin()

0

In [60]:
np.argmin(a2)

0

In [61]:
np.argmax(a2)

11

In [62]:
a2.argmax()

11

In [63]:
a2.min(axis=0)

array([13, 14, 15, 16])

In [64]:
a2.min(axis=1)

array([13, 17, 21])

In [65]:
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [66]:
a2.min(axis = 1)

array([13, 17, 21])

In [67]:
a2.max(axis=1)

array([16, 20, 24])

In [68]:
a2.min(axis = 0)

array([13, 14, 15, 16])

In [69]:
a2.sum(axis = 0)

array([51, 54, 57, 60])

In [70]:
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [72]:
np.sum(a2,axis = 0)

array([51, 54, 57, 60])

In [76]:
np.sum(a2,axis = 1)

array([58, 74, 90])

In [80]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [82]:
np.concatenate((a1,a2),axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [83]:
np.concatenate((a1,a2),axis = 1)

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [85]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
np.split(a,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [89]:
np.split(a,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [90]:
np.split(a,[3])

[array([1, 2, 3]), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [91]:
np.random.random()

0.5411169051738821

In [92]:
np.random.random(5)

array([0.91571675, 0.85633141, 0.64302979, 0.37501767, 0.16872444])

In [93]:
np.random.random((3,5))

array([[0.31458192, 0.38123872, 0.66224053, 0.87368444, 0.58261639],
       [0.04380367, 0.03225811, 0.06636763, 0.56525397, 0.52412834],
       [0.28738053, 0.91528717, 0.40898608, 0.27255666, 0.44700794]])

In [94]:
np.random.random((3,2,3))

array([[[0.1994385 , 0.52868847, 0.86054381],
        [0.92229055, 0.79870686, 0.96493326]],

       [[0.76308177, 0.18731936, 0.25911911],
        [0.40297875, 0.4835862 , 0.61931252]],

       [[0.20828185, 0.10459473, 0.73016217],
        [0.16241188, 0.74662732, 0.98890246]]])

In [95]:
np.random.randint(1,14)

2

In [96]:
np.random.randint(1,14,(2,6))

array([[ 9,  9, 10, 11,  7,  8],
       [ 6, 11,  7,  2,  5,  8]])

In [97]:
np.random.rand(1,14)

array([[0.03751909, 0.47265391, 0.6650767 , 0.8104472 , 0.54242375,
        0.16642334, 0.35927143, 0.09003257, 0.08685035, 0.07895425,
        0.89354321, 0.91968199, 0.54316492, 0.82727507]])

In [98]:
np.random.rand(3,4)

array([[0.73100749, 0.20309899, 0.53295033, 0.81181442],
       [0.92550122, 0.34326943, 0.97949793, 0.01037947],
       [0.14770979, 0.06706849, 0.54082788, 0.49990142]])

In [99]:
a = np.arange(15,28)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [100]:
np.random.choice(a)

21

In [101]:
np.random.permutation(a)

array([26, 18, 15, 21, 27, 22, 19, 25, 20, 16, 17, 24, 23])

In [136]:
np.random.permutation(a)
np.random.choice(a)

19

In [137]:
np.random.normal()

1.032700705792239

In [138]:
np.random.normal(50,15,100)

array([ 54.36301191,  59.50715169,  40.41629166,  75.02351822,
        58.22029505,  20.85988594,  40.02880954,  47.56625413,
        25.05609191,  63.82608912,  24.36514132,  67.04255096,
        28.4039598 ,  33.13409272,  39.39526778,  38.88805677,
        38.05884153,  56.8850941 ,  48.64514284,  57.1858693 ,
        38.11292962,  44.94553176,  40.48234075,  60.40004224,
        55.63568958,  56.55636252,  78.15459931,  46.76267707,
        63.57401177,  49.23696476,  70.99206584,  46.81479167,
        57.43580019,  29.33131231,  45.97872697,  38.88646391,
        38.28888884,  57.5331294 ,  70.13743699,  23.66724869,
        42.88582014,  71.88207026,  78.54260064,  24.48838123,
        60.03511684, 102.61861467,  56.23241382,  67.38014958,
        48.84213838,  26.76264533,  73.89273376,  32.94012353,
        20.54395737,  41.17234097,  41.06041351,  38.20755899,
        40.44365352,  34.76327101,  46.25490137,  57.59629693,
        55.89705156,  34.19501654,  51.07760807,  46.19